#*****************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# test2.tcl: Tcl script for re-creating project '_xil_proj_name_'
#
# Generated by Vivado on Tue Jul 18 22:18:05 +0800 2023
# IP Build 3064653 on Wed Nov 18 14:17:31 MST 2020
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (test2.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set paths [list \
   [file normalize "$origin_dir/../Ip_core"] \
  ]
  foreach ipath $paths {
    if { ![file isdirectory $ipath] } {
      puts " Could not access $ipath "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "_xil_proj_name_"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "test2.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../prj_zyf"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xcku040-ffva1156-2-i

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "compxlib.modelsim_compiled_library_dir" -value "E:/sim_lib" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip.user_files_dir" -value "$proj_dir/prj_zyf2.ip_user_files" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xcku040-ffva1156-2-i" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/prj_zyf2.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "17" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "17" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "17" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "17" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "17" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "17" -objects $obj
set_property -name "webtalk.xcelium_export_sim" -value "3" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "17" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
if { $obj != {} } {
   set_property "ip_repo_paths" "[file normalize "$origin_dir/../Ip_core"]" $obj

   # Rebuild user ip_repo's index before adding any source files
   update_ip_catalog -rebuild
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "system_wrapper" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xcku040-ffva1156-2-i" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "system_wrapper" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added


# Proc to create BD system
proc cr_bd_system { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name system

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:util_vector_logic:2.0\
  xilinx.com:ip:axis_data_fifo:2.0\
  xilinx.com:ip:axis_dwidth_converter:1.1\
  xilinx.com:ip:ila:6.2\
  xilinx.com:ip:axis_clock_converter:1.1\
  xilinx.com:user:tcpip_core:1.0\
  xilinx.com:ip:axi_gpio:2.0\
  xilinx.com:ip:axi_iic:2.0\
  xilinx.com:ip:axi_intc:4.1\
  xilinx.com:ip:axi_quad_spi:3.2\
  xilinx.com:ip:axi_timer:2.0\
  xilinx.com:ip:mdm:3.2\
  xilinx.com:ip:microblaze:11.0\
  xilinx.com:ip:proc_sys_reset:5.0\
  xilinx.com:user:spi_io:1.0\
  xilinx.com:ip:xlconcat:2.1\
  xilinx.com:user:fifo_top:1.0\
  xilinx.com:user:mdyFmcAd9653_top:1.0\
  xilinx.com:user:trigger_top:1.0\
  ustc:user:ddr_ctrl_top:2.1\
  xilinx.com:ip:axi_bram_ctrl:4.1\
  ustc:awg1.0:cpu_ram:1.0\
  xilinx.com:ip:blk_mem_gen:8.4\
  xilinx.com:ip:lmb_bram_if_cntlr:4.0\
  xilinx.com:ip:lmb_v10:3.0\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  
# Hierarchical cell: mb_lmb
proc create_hier_cell_mb_lmb { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_mb_lmb() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode MirroredMaster -vlnv xilinx.com:interface:lmb_rtl:1.0 DLMB

  create_bd_intf_pin -mode MirroredMaster -vlnv xilinx.com:interface:lmb_rtl:1.0 ILMB


  # Create pins
  create_bd_pin -dir I -type clk LMB_Clk
  create_bd_pin -dir I -type rst LMB_Rst

  # Create instance: blk_mem_gen_0, and set properties
  set blk_mem_gen_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:blk_mem_gen:8.4 blk_mem_gen_0 ]
  set_property -dict [ list \
   CONFIG.Assume_Synchronous_Clk {true} \
   CONFIG.EN_SAFETY_CKT {false} \
   CONFIG.Enable_B {Use_ENB_Pin} \
   CONFIG.Memory_Type {True_Dual_Port_RAM} \
   CONFIG.Port_B_Clock {100} \
   CONFIG.Port_B_Enable_Rate {100} \
   CONFIG.Port_B_Write_Rate {50} \
   CONFIG.Use_RSTB_Pin {true} \
 ] $blk_mem_gen_0

  # Create instance: dlmb_bram_if_cntlr, and set properties
  set dlmb_bram_if_cntlr [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_bram_if_cntlr:4.0 dlmb_bram_if_cntlr ]

  # Create instance: dlmb_v10, and set properties
  set dlmb_v10 [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_v10:3.0 dlmb_v10 ]

  # Create instance: ilmb_bram_if_cntlr, and set properties
  set ilmb_bram_if_cntlr [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_bram_if_cntlr:4.0 ilmb_bram_if_cntlr ]

  # Create instance: ilmb_v10, and set properties
  set ilmb_v10 [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_v10:3.0 ilmb_v10 ]

  # Create interface connections
  connect_bd_intf_net -intf_net Conn [get_bd_intf_pins dlmb_bram_if_cntlr/SLMB] [get_bd_intf_pins dlmb_v10/LMB_Sl_0]
  connect_bd_intf_net -intf_net Conn1 [get_bd_intf_pins ilmb_bram_if_cntlr/SLMB] [get_bd_intf_pins ilmb_v10/LMB_Sl_0]
  connect_bd_intf_net -intf_net Conn2 [get_bd_intf_pins DLMB] [get_bd_intf_pins dlmb_v10/LMB_M]
  connect_bd_intf_net -intf_net Conn3 [get_bd_intf_pins ILMB] [get_bd_intf_pins ilmb_v10/LMB_M]
  connect_bd_intf_net -intf_net dlmb_bram_if_cntlr_BRAM_PORT [get_bd_intf_pins blk_mem_gen_0/BRAM_PORTA] [get_bd_intf_pins dlmb_bram_if_cntlr/BRAM_PORT]
  connect_bd_intf_net -intf_net ilmb_bram_if_cntlr_BRAM_PORT [get_bd_intf_pins blk_mem_gen_0/BRAM_PORTB] [get_bd_intf_pins ilmb_bram_if_cntlr/BRAM_PORT]

  # Create port connections
  connect_bd_net -net LMB_Rst_1 [get_bd_pins LMB_Rst] [get_bd_pins dlmb_bram_if_cntlr/LMB_Rst] [get_bd_pins dlmb_v10/SYS_Rst] [get_bd_pins ilmb_bram_if_cntlr/LMB_Rst] [get_bd_pins ilmb_v10/SYS_Rst]
  connect_bd_net -net Net [get_bd_pins LMB_Clk] [get_bd_pins dlmb_bram_if_cntlr/LMB_Clk] [get_bd_pins dlmb_v10/LMB_Clk] [get_bd_pins ilmb_bram_if_cntlr/LMB_Clk] [get_bd_pins ilmb_v10/LMB_Clk]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  
# Hierarchical cell: cpu_ram
proc create_hier_cell_cpu_ram { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_cpu_ram() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 cmu2cpu_axis

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 cpu2cmu_axis

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 cpu_bram_S_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 cpu_ram_S_AXI


  # Create pins
  create_bd_pin -dir I cmu_clk
  create_bd_pin -dir I cmu_rstn
  create_bd_pin -dir I cpu_clk
  create_bd_pin -dir O cpu_ram_intr_o
  create_bd_pin -dir I cpu_rstn
  create_bd_pin -dir I -type rst rst

  # Create instance: axi_bram_ctrl_0, and set properties
  set axi_bram_ctrl_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_bram_ctrl:4.1 axi_bram_ctrl_0 ]
  set_property -dict [ list \
   CONFIG.SINGLE_PORT_BRAM {1} \
 ] $axi_bram_ctrl_0

  # Create instance: axis_clock_converter_0, and set properties
  set axis_clock_converter_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_clock_converter:1.1 axis_clock_converter_0 ]

  # Create instance: axis_clock_converter_1, and set properties
  set axis_clock_converter_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_clock_converter:1.1 axis_clock_converter_1 ]

  # Create instance: cpu_ram_0, and set properties
  set cpu_ram_0 [ create_bd_cell -type ip -vlnv ustc:awg1.0:cpu_ram:1.0 cpu_ram_0 ]
  set_property -dict [ list \
   CONFIG.DEBUG {true} \
 ] $cpu_ram_0

  # Create interface connections
  connect_bd_intf_net -intf_net axi_bram_ctrl_0_BRAM_PORTA [get_bd_intf_pins axi_bram_ctrl_0/BRAM_PORTA] [get_bd_intf_pins cpu_ram_0/bram_a]
  connect_bd_intf_net -intf_net axis_clock_converter_0_M_AXIS [get_bd_intf_pins axis_clock_converter_0/M_AXIS] [get_bd_intf_pins cpu_ram_0/s_axis]
  connect_bd_intf_net -intf_net axis_clock_converter_1_M_AXIS [get_bd_intf_pins cpu2cmu_axis] [get_bd_intf_pins axis_clock_converter_1/M_AXIS]
  connect_bd_intf_net -intf_net cmu2cpu_axis_1 [get_bd_intf_pins cmu2cpu_axis] [get_bd_intf_pins axis_clock_converter_0/S_AXIS]
  connect_bd_intf_net -intf_net cpu_bram_S_AXI_1 [get_bd_intf_pins cpu_bram_S_AXI] [get_bd_intf_pins axi_bram_ctrl_0/S_AXI]
  connect_bd_intf_net -intf_net cpu_ram_0_m_axis [get_bd_intf_pins axis_clock_converter_1/S_AXIS] [get_bd_intf_pins cpu_ram_0/m_axis]
  connect_bd_intf_net -intf_net cpu_ram_S_AXI_1 [get_bd_intf_pins cpu_ram_S_AXI] [get_bd_intf_pins cpu_ram_0/S_AXI]

  # Create port connections
  connect_bd_net -net cmu_clk_1 [get_bd_pins cmu_clk] [get_bd_pins axis_clock_converter_0/s_axis_aclk] [get_bd_pins axis_clock_converter_1/m_axis_aclk]
  connect_bd_net -net cmu_rstn_1 [get_bd_pins cmu_rstn] [get_bd_pins axis_clock_converter_0/s_axis_aresetn] [get_bd_pins axis_clock_converter_1/m_axis_aresetn]
  connect_bd_net -net cpu_clk_1 [get_bd_pins cpu_clk] [get_bd_pins axi_bram_ctrl_0/s_axi_aclk] [get_bd_pins axis_clock_converter_0/m_axis_aclk] [get_bd_pins axis_clock_converter_1/s_axis_aclk] [get_bd_pins cpu_ram_0/S_AXI_aclk] [get_bd_pins cpu_ram_0/clk]
  connect_bd_net -net cpu_ram_0_intr_o [get_bd_pins cpu_ram_intr_o] [get_bd_pins cpu_ram_0/intr_o]
  connect_bd_net -net cpu_rstn_1 [get_bd_pins cpu_rstn] [get_bd_pins axi_bram_ctrl_0/s_axi_aresetn] [get_bd_pins axis_clock_converter_0/m_axis_aresetn] [get_bd_pins axis_clock_converter_1/s_axis_aresetn] [get_bd_pins cpu_ram_0/S_AXI_aresetn]
  connect_bd_net -net rst_1 [get_bd_pins rst] [get_bd_pins cpu_ram_0/rst]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  
# Hierarchical cell: MEM_TOP
proc create_hier_cell_MEM_TOP { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_MEM_TOP() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 M_AXIS

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 S_AXIS

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 S_daq2mem_axis

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 c0_ddr4_0


  # Create pins
  create_bd_pin -dir I c0_sys_clk_n
  create_bd_pin -dir I c0_sys_clk_p
  create_bd_pin -dir O -type clk cpu_clk
  create_bd_pin -dir I -type rst cpu_rstn
  create_bd_pin -dir I -type clk daq_clk
  create_bd_pin -dir I -type rst daq_rstn
  create_bd_pin -dir I -type clk eth_clk
  create_bd_pin -dir I -type rst eth_rstn
  create_bd_pin -dir O -type clk mem_clk
  create_bd_pin -dir O -type rst mem_rstn
  create_bd_pin -dir I -type rst sys_rst

  # Create instance: axis_clock_converter_0, and set properties
  set axis_clock_converter_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_clock_converter:1.1 axis_clock_converter_0 ]

  # Create instance: axis_clock_converter_1, and set properties
  set axis_clock_converter_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_clock_converter:1.1 axis_clock_converter_1 ]

  # Create instance: axis_interconnect_0, and set properties
  set axis_interconnect_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_interconnect:2.1 axis_interconnect_0 ]
  set_property -dict [ list \
   CONFIG.ARB_ON_MAX_XFERS {0} \
   CONFIG.ARB_ON_TLAST {1} \
   CONFIG.NUM_MI {1} \
   CONFIG.NUM_SI {2} \
   CONFIG.S00_FIFO_DEPTH {32} \
   CONFIG.S01_FIFO_DEPTH {32} \
 ] $axis_interconnect_0

  # Create instance: ddr_ctrl_top_1, and set properties
  set ddr_ctrl_top_1 [ create_bd_cell -type ip -vlnv ustc:user:ddr_ctrl_top:2.1 ddr_ctrl_top_1 ]

  # Create interface connections
  connect_bd_intf_net -intf_net Conn1 [get_bd_intf_pins c0_ddr4_0] [get_bd_intf_pins ddr_ctrl_top_1/c0_ddr4]
  connect_bd_intf_net -intf_net S_AXI_1 [get_bd_intf_pins S_AXI] [get_bd_intf_pins ddr_ctrl_top_1/S_AXI]
  connect_bd_intf_net -intf_net S_daq2mem_axis_1 [get_bd_intf_pins S_daq2mem_axis] [get_bd_intf_pins axis_clock_converter_0/S_AXIS]
  connect_bd_intf_net -intf_net axis_clock_converter_0_M_AXIS [get_bd_intf_pins axis_clock_converter_0/M_AXIS] [get_bd_intf_pins axis_interconnect_0/S01_AXIS]
  connect_bd_intf_net -intf_net axis_clock_converter_1_M_AXIS [get_bd_intf_pins axis_clock_converter_1/M_AXIS] [get_bd_intf_pins axis_interconnect_0/S00_AXIS]
  connect_bd_intf_net -intf_net axis_interconnect_0_M00_AXIS [get_bd_intf_pins axis_interconnect_0/M00_AXIS] [get_bd_intf_pins ddr_ctrl_top_1/S_AXIS]
  connect_bd_intf_net -intf_net ddr_ctrl_top_1_M_AXIS [get_bd_intf_pins M_AXIS] [get_bd_intf_pins ddr_ctrl_top_1/M_AXIS]
  connect_bd_intf_net -intf_net udp_2_mem_process_0_m_axis [get_bd_intf_pins S_AXIS] [get_bd_intf_pins axis_clock_converter_1/S_AXIS]

  # Create port connections
  connect_bd_net -net ACLK_1 [get_bd_pins mem_clk] [get_bd_pins axis_clock_converter_0/m_axis_aclk] [get_bd_pins axis_clock_converter_1/m_axis_aclk] [get_bd_pins axis_interconnect_0/ACLK] [get_bd_pins axis_interconnect_0/M00_AXIS_ACLK] [get_bd_pins axis_interconnect_0/S00_AXIS_ACLK] [get_bd_pins axis_interconnect_0/S01_AXIS_ACLK] [get_bd_pins ddr_ctrl_top_1/AXIS_ACLK] [get_bd_pins ddr_ctrl_top_1/ui_clk]
  connect_bd_net -net Net [get_bd_pins eth_clk] [get_bd_pins axis_clock_converter_1/s_axis_aclk]
  connect_bd_net -net Net1 [get_bd_pins eth_rstn] [get_bd_pins axis_clock_converter_1/s_axis_aresetn]
  connect_bd_net -net c0_sys_clk_n_1 [get_bd_pins c0_sys_clk_n] [get_bd_pins ddr_ctrl_top_1/c0_sys_clk_n]
  connect_bd_net -net c0_sys_clk_p_1 [get_bd_pins c0_sys_clk_p] [get_bd_pins ddr_ctrl_top_1/c0_sys_clk_p]
  connect_bd_net -net clk_wiz_clk_out1 [get_bd_pins cpu_clk] [get_bd_pins ddr_ctrl_top_1/S_AXI_aclk] [get_bd_pins ddr_ctrl_top_1/cpu_clk]
  connect_bd_net -net daq_clk_1 [get_bd_pins daq_clk] [get_bd_pins axis_clock_converter_0/s_axis_aclk]
  connect_bd_net -net daq_rstn_1 [get_bd_pins daq_rstn] [get_bd_pins axis_clock_converter_0/s_axis_aresetn]
  connect_bd_net -net ddr_ctrl_top_0_ui_rst_n [get_bd_pins mem_rstn] [get_bd_pins axis_clock_converter_0/m_axis_aresetn] [get_bd_pins axis_clock_converter_1/m_axis_aresetn] [get_bd_pins axis_interconnect_0/ARESETN] [get_bd_pins axis_interconnect_0/M00_AXIS_ARESETN] [get_bd_pins axis_interconnect_0/S00_AXIS_ARESETN] [get_bd_pins axis_interconnect_0/S01_AXIS_ARESETN] [get_bd_pins ddr_ctrl_top_1/AXIS_ARESETN] [get_bd_pins ddr_ctrl_top_1/ui_rst_n]
  connect_bd_net -net rst_clk_wiz_100M_peripheral_aresetn [get_bd_pins cpu_rstn] [get_bd_pins ddr_ctrl_top_1/S_AXI_aresetn]
  connect_bd_net -net rst_clk_wiz_100M_peripheral_reset [get_bd_pins sys_rst] [get_bd_pins ddr_ctrl_top_1/sys_rst]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  
# Hierarchical cell: DAQ_TOP
proc create_hier_cell_DAQ_TOP { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_DAQ_TOP() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S_AXI_DAQ

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 m_rd_axis


  # Create pins
  create_bd_pin -dir O -from 0 -to 0 AD1_CSB
  create_bd_pin -dir O -from 0 -to 0 ADC_SCLK
  create_bd_pin -dir O -from 0 -to 0 ADC_SDIO
  create_bd_pin -dir I -from 0 -to 0 CLK_200M_N
  create_bd_pin -dir I -from 0 -to 0 CLK_200M_P
  create_bd_pin -dir I -from 0 -to 0 EXT_PLL_LOCK
  create_bd_pin -dir O -from 0 -to 0 F_CLK_SEL
  create_bd_pin -dir O -from 3 -to 0 LED
  create_bd_pin -dir I -from 0 -to 0 PLL_CLK_N
  create_bd_pin -dir I -from 0 -to 0 PLL_CLK_P
  create_bd_pin -dir O -from 0 -to 0 PLL_CS
  create_bd_pin -dir O -from 0 -to 0 PLL_RESETN
  create_bd_pin -dir O -from 0 -to 0 PLL_SCLK
  create_bd_pin -dir O -from 0 -to 0 PLL_SDIO
  create_bd_pin -dir I -from 0 -to 0 PLL_SDO
  create_bd_pin -dir I -from 9 -to 0 ad9653_ifc_n_0
  create_bd_pin -dir I -from 9 -to 0 ad9653_ifc_p_0
  create_bd_pin -dir O -from 0 -to 0 adc_sync_0
  create_bd_pin -dir I cpu_clk
  create_bd_pin -dir I cpu_rstn
  create_bd_pin -dir O -from 0 -to 0 daq_clk
  create_bd_pin -dir O -from 0 -to 0 daq_rstn
  create_bd_pin -dir I external_trig_0
  create_bd_pin -dir I -type rst reset

  # Create instance: axi_interconnect_0, and set properties
  set axi_interconnect_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_interconnect_0 ]

  # Create instance: fifo_top_0, and set properties
  set fifo_top_0 [ create_bd_cell -type ip -vlnv xilinx.com:user:fifo_top:1.0 fifo_top_0 ]
  set_property -dict [ list \
   CONFIG.TRIGGER_DATA_WIDTH {128} \
 ] $fifo_top_0

  # Create instance: mdyFmcAd9653_top_0, and set properties
  set mdyFmcAd9653_top_0 [ create_bd_cell -type ip -vlnv xilinx.com:user:mdyFmcAd9653_top:1.0 mdyFmcAd9653_top_0 ]

  # Create instance: proc_sys_reset_0, and set properties
  set proc_sys_reset_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 proc_sys_reset_0 ]

  # Create instance: trigger_top_0, and set properties
  set trigger_top_0 [ create_bd_cell -type ip -vlnv xilinx.com:user:trigger_top:1.0 trigger_top_0 ]

  # Create interface connections
  connect_bd_intf_net -intf_net S_AXI_DAQ_1 [get_bd_intf_pins S_AXI_DAQ] [get_bd_intf_pins axi_interconnect_0/S00_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M00_AXI [get_bd_intf_pins axi_interconnect_0/M00_AXI] [get_bd_intf_pins trigger_top_0/S_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M01_AXI [get_bd_intf_pins axi_interconnect_0/M01_AXI] [get_bd_intf_pins fifo_top_0/S_AXI]
  connect_bd_intf_net -intf_net fifo_top_0_rd_axis [get_bd_intf_pins m_rd_axis] [get_bd_intf_pins fifo_top_0/rd_axis]
  connect_bd_intf_net -intf_net mdyFmcAd9653_top_0_M_DAQ [get_bd_intf_pins fifo_top_0/adc_axis] [get_bd_intf_pins mdyFmcAd9653_top_0/M_DAQ]
  connect_bd_intf_net -intf_net trigger_top_0_M_AXI [get_bd_intf_pins fifo_top_0/trigger_axis] [get_bd_intf_pins trigger_top_0/M_AXI]

  # Create port connections
  connect_bd_net -net CLK_200M_N_1 [get_bd_pins CLK_200M_N] [get_bd_pins mdyFmcAd9653_top_0/CLK_200M_N]
  connect_bd_net -net CLK_200M_P_1 [get_bd_pins CLK_200M_P] [get_bd_pins mdyFmcAd9653_top_0/CLK_200M_P]
  connect_bd_net -net EXT_PLL_LOCK_1 [get_bd_pins EXT_PLL_LOCK] [get_bd_pins mdyFmcAd9653_top_0/EXT_PLL_LOCK]
  connect_bd_net -net PLL_CLK_N_1 [get_bd_pins PLL_CLK_N] [get_bd_pins mdyFmcAd9653_top_0/PLL_CLK_N]
  connect_bd_net -net PLL_CLK_P_1 [get_bd_pins PLL_CLK_P] [get_bd_pins mdyFmcAd9653_top_0/PLL_CLK_P]
  connect_bd_net -net PLL_SDO_1 [get_bd_pins PLL_SDO] [get_bd_pins mdyFmcAd9653_top_0/PLL_SDO]
  connect_bd_net -net ad9653_ifc_n_0_1 [get_bd_pins ad9653_ifc_n_0] [get_bd_pins mdyFmcAd9653_top_0/ad9653_ifc_n]
  connect_bd_net -net ad9653_ifc_p_0_1 [get_bd_pins ad9653_ifc_p_0] [get_bd_pins mdyFmcAd9653_top_0/ad9653_ifc_p]
  connect_bd_net -net cpu_clk_1 [get_bd_pins cpu_clk] [get_bd_pins axi_interconnect_0/ACLK] [get_bd_pins axi_interconnect_0/M00_ACLK] [get_bd_pins axi_interconnect_0/M01_ACLK] [get_bd_pins axi_interconnect_0/S00_ACLK] [get_bd_pins fifo_top_0/S_AXI_aclk] [get_bd_pins trigger_top_0/S_AXI_aclk]
  connect_bd_net -net cpu_rstn_1 [get_bd_pins cpu_rstn] [get_bd_pins axi_interconnect_0/ARESETN] [get_bd_pins axi_interconnect_0/M00_ARESETN] [get_bd_pins axi_interconnect_0/M01_ARESETN] [get_bd_pins axi_interconnect_0/S00_ARESETN] [get_bd_pins fifo_top_0/S_AXI_aresetn] [get_bd_pins proc_sys_reset_0/ext_reset_in] [get_bd_pins trigger_top_0/S_AXI_aresetn]
  connect_bd_net -net external_trig_0_1 [get_bd_pins external_trig_0] [get_bd_pins trigger_top_0/external_trig]
  connect_bd_net -net mdyFmcAd9653_top_0_AD1_CSB [get_bd_pins AD1_CSB] [get_bd_pins mdyFmcAd9653_top_0/AD1_CSB]
  connect_bd_net -net mdyFmcAd9653_top_0_ADC_SCLK [get_bd_pins ADC_SCLK] [get_bd_pins mdyFmcAd9653_top_0/ADC_SCLK]
  connect_bd_net -net mdyFmcAd9653_top_0_ADC_SDIO [get_bd_pins ADC_SDIO] [get_bd_pins mdyFmcAd9653_top_0/ADC_SDIO]
  connect_bd_net -net mdyFmcAd9653_top_0_ADC_SYNC [get_bd_pins adc_sync_0] [get_bd_pins mdyFmcAd9653_top_0/ADC_SYNC]
  connect_bd_net -net mdyFmcAd9653_top_0_F_CLK_SEL [get_bd_pins F_CLK_SEL] [get_bd_pins mdyFmcAd9653_top_0/F_CLK_SEL]
  connect_bd_net -net mdyFmcAd9653_top_0_LED [get_bd_pins LED] [get_bd_pins mdyFmcAd9653_top_0/LED]
  connect_bd_net -net mdyFmcAd9653_top_0_PLL_CS [get_bd_pins PLL_CS] [get_bd_pins mdyFmcAd9653_top_0/PLL_CS]
  connect_bd_net -net mdyFmcAd9653_top_0_PLL_RESETN [get_bd_pins PLL_RESETN] [get_bd_pins mdyFmcAd9653_top_0/PLL_RESETN]
  connect_bd_net -net mdyFmcAd9653_top_0_PLL_SCLK [get_bd_pins PLL_SCLK] [get_bd_pins mdyFmcAd9653_top_0/PLL_SCLK]
  connect_bd_net -net mdyFmcAd9653_top_0_PLL_SDIO [get_bd_pins PLL_SDIO] [get_bd_pins mdyFmcAd9653_top_0/PLL_SDIO]
  connect_bd_net -net mdyFmcAd9653_top_0_clk_125M [get_bd_pins fifo_top_0/clk] [get_bd_pins mdyFmcAd9653_top_0/clk_125M] [get_bd_pins proc_sys_reset_0/slowest_sync_clk] [get_bd_pins trigger_top_0/clk]
  connect_bd_net -net proc_sys_reset_0_interconnect_aresetn [get_bd_pins daq_rstn] [get_bd_pins proc_sys_reset_0/interconnect_aresetn]
  connect_bd_net -net reset_1 [get_bd_pins reset] [get_bd_pins fifo_top_0/rst]

  # Perform GUI Layout
  regenerate_bd_layout -hierarchy [get_bd_cells /DAQ_TOP] -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"0.843663",
   "Default View_TopLeft":"-241,217",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.0r6  2020-01-29 bk=1.5227 VDI=41 GEI=36 GUI=JA:10.0 non-TLS
#  -string -flagsOSRD
preplace port S_AXI_DAQ -pg 1 -lvl 0 -x -30 -y 290 -defaultsOSRD
preplace port m_rd_axis -pg 1 -lvl 4 -x 1380 -y 380 -defaultsOSRD
preplace port cpu_clk -pg 1 -lvl 0 -x -30 -y 310 -defaultsOSRD
preplace port cpu_rstn -pg 1 -lvl 0 -x -30 -y 330 -defaultsOSRD
preplace port external_trig_0 -pg 1 -lvl 0 -x -30 -y 540 -defaultsOSRD
preplace port reset -pg 1 -lvl 0 -x -30 -y 610 -defaultsOSRD
preplace portBus AD1_CSB -pg 1 -lvl 4 -x 1380 -y 210 -defaultsOSRD
preplace portBus ADC_SCLK -pg 1 -lvl 4 -x 1380 -y 190 -defaultsOSRD
preplace portBus ADC_SDIO -pg 1 -lvl 4 -x 1380 -y 230 -defaultsOSRD
preplace portBus CLK_200M_N -pg 1 -lvl 0 -x -30 -y 110 -defaultsOSRD
preplace portBus CLK_200M_P -pg 1 -lvl 0 -x -30 -y 90 -defaultsOSRD
preplace portBus EXT_PLL_LOCK -pg 1 -lvl 0 -x -30 -y 190 -defaultsOSRD
preplace portBus F_CLK_SEL -pg 1 -lvl 4 -x 1380 -y 70 -defaultsOSRD
preplace portBus LED -pg 1 -lvl 4 -x 1380 -y 90 -defaultsOSRD
preplace portBus PLL_CLK_N -pg 1 -lvl 0 -x -30 -y 150 -defaultsOSRD
preplace portBus PLL_CLK_P -pg 1 -lvl 0 -x -30 -y 130 -defaultsOSRD
preplace portBus PLL_CS -pg 1 -lvl 4 -x 1380 -y 130 -defaultsOSRD
preplace portBus PLL_RESETN -pg 1 -lvl 4 -x 1380 -y 170 -defaultsOSRD
preplace portBus PLL_SCLK -pg 1 -lvl 4 -x 1380 -y 110 -defaultsOSRD
preplace portBus PLL_SDIO -pg 1 -lvl 4 -x 1380 -y 150 -defaultsOSRD
preplace portBus PLL_SDO -pg 1 -lvl 0 -x -30 -y 170 -defaultsOSRD
preplace portBus ad9653_ifc_n_0 -pg 1 -lvl 0 -x -30 -y 230 -defaultsOSRD
preplace portBus ad9653_ifc_p_0 -pg 1 -lvl 0 -x -30 -y 210 -defaultsOSRD
preplace portBus adc_sync_0 -pg 1 -lvl 4 -x 1380 -y 250 -defaultsOSRD
preplace portBus daq_clk -pg 1 -lvl 4 -x 1380 -y 270 -defaultsOSRD
preplace portBus daq_rstn -pg 1 -lvl 4 -x 1380 -y 620 -defaultsOSRD
preplace inst axi_interconnect_0 -pg 1 -lvl 1 -x 460 -y 370 -defaultsOSRD
preplace inst mdyFmcAd9653_top_0 -pg 1 -lvl 2 -x 800 -y 160 -defaultsOSRD
preplace inst proc_sys_reset_0 -pg 1 -lvl 3 -x 1180 -y 1160 -defaultsOSRD
preplace inst fifo_top_0 -pg 1 -lvl 3 -x 1180 -y 680 -defaultsOSRD
preplace inst trigger_top_0 -pg 1 -lvl 2 -x 800 -y 450 -defaultsOSRD
preplace netloc CLK_200M_N_1 1 0 2 NJ 110 NJ
preplace netloc CLK_200M_P_1 1 0 2 NJ 90 NJ
preplace netloc EXT_PLL_LOCK_1 1 0 2 NJ 190 NJ
preplace netloc PLL_CLK_N_1 1 0 2 NJ 150 NJ
preplace netloc PLL_CLK_P_1 1 0 2 NJ 130 NJ
preplace netloc PLL_SDO_1 1 0 2 NJ 170 NJ
preplace netloc ad9653_ifc_n_0_1 1 0 2 NJ 230 NJ
preplace netloc ad9653_ifc_p_0_1 1 0 2 NJ 210 NJ
preplace netloc cpu_clk_1 1 0 3 0 510 620 870 970J
preplace netloc cpu_rstn_1 1 0 3 -10 520 630 880 960
preplace netloc mdyFmcAd9653_top_0_AD1_CSB 1 2 2 NJ 210 NJ
preplace netloc mdyFmcAd9653_top_0_ADC_SCLK 1 2 2 NJ 190 NJ
preplace netloc mdyFmcAd9653_top_0_ADC_SDIO 1 2 2 NJ 230 NJ
preplace netloc mdyFmcAd9653_top_0_ADC_SYNC 1 2 2 NJ 250 NJ
preplace netloc mdyFmcAd9653_top_0_F_CLK_SEL 1 2 2 NJ 70 NJ
preplace netloc mdyFmcAd9653_top_0_LED 1 2 2 NJ 90 NJ
preplace netloc mdyFmcAd9653_top_0_PLL_CS 1 2 2 NJ 130 NJ
preplace netloc mdyFmcAd9653_top_0_PLL_RESETN 1 2 2 NJ 170 NJ
preplace netloc mdyFmcAd9653_top_0_PLL_SCLK 1 2 2 NJ 110 NJ
preplace netloc mdyFmcAd9653_top_0_PLL_SDIO 1 2 2 NJ 150 NJ
preplace netloc proc_sys_reset_0_interconnect_aresetn 1 3 1 1360J 620n
preplace netloc reset_1 1 0 3 NJ 610 610J 890 NJ
preplace netloc mdyFmcAd9653_top_0_clk_125M 1 1 2 640 340 980
preplace netloc external_trig_0_1 1 0 2 NJ 540 610
preplace netloc mdyFmcAd9653_top_0_M_DAQ 1 2 1 1000 50n
preplace netloc fifo_top_0_rd_axis 1 3 1 1350J 380n
preplace netloc axi_interconnect_0_M01_AXI 1 1 2 620 350 990J
preplace netloc S_AXI_DAQ_1 1 0 1 NJ 290
preplace netloc axi_interconnect_0_M00_AXI 1 1 1 630 360n
preplace netloc trigger_top_0_M_AXI 1 2 1 N 450
levelinfo -pg 1 -30 460 800 1180 1380
pagesize -pg 1 -db -bbox -sgen -220 -10 1550 1320
"
}

  # Restore current instance
  current_bd_instance $oldCurInst
}
  
# Hierarchical cell: CPU_TOP
proc create_hier_cell_CPU_TOP { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_CPU_TOP() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 GPIO2_0

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 GPIO_0

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:iic_rtl:1.0 IIC_0

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M00_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M02_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M10_AXI_DAQ

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 cmu2cpu_axis

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 cpu2cmu_axis


  # Create pins
  create_bd_pin -dir I cmu_clk
  create_bd_pin -dir I cmu_rstn
  create_bd_pin -dir I -type clk cpu_clk
  create_bd_pin -dir O -from 0 -to 0 -type rst cpu_rstn
  create_bd_pin -dir I -type rst ext_reset_in
  create_bd_pin -dir O -from 2 -to 0 gpo_0
  create_bd_pin -dir O -from 0 -to 0 -type rst peripheral_reset
  create_bd_pin -dir O -from 2 -to 0 spi_clks_0
  create_bd_pin -dir O -from 2 -to 0 spi_csns_0
  create_bd_pin -dir I -from 2 -to 0 spi_sdis_0
  create_bd_pin -dir O -from 2 -to 0 spi_sdos_0

  # Create instance: axi_gpio_0, and set properties
  set axi_gpio_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_0 ]
  set_property -dict [ list \
   CONFIG.C_ALL_INPUTS_2 {1} \
   CONFIG.C_ALL_OUTPUTS {1} \
   CONFIG.C_ALL_OUTPUTS_2 {0} \
   CONFIG.C_GPIO2_WIDTH {8} \
   CONFIG.C_GPIO_WIDTH {8} \
   CONFIG.C_IS_DUAL {1} \
 ] $axi_gpio_0

  # Create instance: axi_iic_0, and set properties
  set axi_iic_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_iic:2.0 axi_iic_0 ]
  set_property -dict [ list \
   CONFIG.C_DEFAULT_VALUE {0xFF} \
   CONFIG.C_GPO_WIDTH {3} \
   CONFIG.C_SCL_INERTIAL_DELAY {5} \
   CONFIG.C_SDA_INERTIAL_DELAY {5} \
 ] $axi_iic_0

  # Create instance: axi_intc_0, and set properties
  set axi_intc_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_intc:4.1 axi_intc_0 ]

  # Create instance: axi_quad_spi_0, and set properties
  set axi_quad_spi_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_quad_spi:3.2 axi_quad_spi_0 ]
  set_property -dict [ list \
   CONFIG.C_NUM_SS_BITS {3} \
 ] $axi_quad_spi_0

  # Create instance: axi_timer_0, and set properties
  set axi_timer_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_timer:2.0 axi_timer_0 ]

  # Create instance: cpu_ram
  create_hier_cell_cpu_ram $hier_obj cpu_ram

  # Create instance: mb_lmb
  create_hier_cell_mb_lmb $hier_obj mb_lmb

  # Create instance: mdm_0, and set properties
  set mdm_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:mdm:3.2 mdm_0 ]
  set_property -dict [ list \
   CONFIG.C_DBG_MEM_ACCESS {0} \
   CONFIG.C_DBG_REG_ACCESS {0} \
   CONFIG.C_S_AXI_ADDR_WIDTH {4} \
   CONFIG.C_USE_UART {1} \
 ] $mdm_0

  # Create instance: microblaze_0, and set properties
  set microblaze_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:microblaze:11.0 microblaze_0 ]
  set_property -dict [ list \
   CONFIG.C_ADDR_TAG_BITS {0} \
   CONFIG.C_AREA_OPTIMIZED {0} \
   CONFIG.C_DCACHE_ADDR_TAG {0} \
   CONFIG.C_D_AXI {1} \
 ] $microblaze_0

  # Create instance: microblaze_0_axi_periph, and set properties
  set microblaze_0_axi_periph [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 microblaze_0_axi_periph ]
  set_property -dict [ list \
   CONFIG.NUM_MI {11} \
 ] $microblaze_0_axi_periph

  # Create instance: rst_clk_wiz_100M, and set properties
  set rst_clk_wiz_100M [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 rst_clk_wiz_100M ]

  # Create instance: spi_io_0, and set properties
  set spi_io_0 [ create_bd_cell -type ip -vlnv xilinx.com:user:spi_io:1.0 spi_io_0 ]

  # Create instance: xlconcat_0, and set properties
  set xlconcat_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat:2.1 xlconcat_0 ]
  set_property -dict [ list \
   CONFIG.NUM_PORTS {3} \
 ] $xlconcat_0

  # Create interface connections
  connect_bd_intf_net -intf_net Conn1 [get_bd_intf_pins GPIO_0] [get_bd_intf_pins axi_gpio_0/GPIO]
  connect_bd_intf_net -intf_net Conn2 [get_bd_intf_pins GPIO2_0] [get_bd_intf_pins axi_gpio_0/GPIO2]
  connect_bd_intf_net -intf_net Conn3 [get_bd_intf_pins IIC_0] [get_bd_intf_pins axi_iic_0/IIC]
  connect_bd_intf_net -intf_net axi_intc_0_interrupt [get_bd_intf_pins axi_intc_0/interrupt] [get_bd_intf_pins microblaze_0/INTERRUPT]
  connect_bd_intf_net -intf_net cpu_ram_cpu2udp_axis [get_bd_intf_pins cpu2cmu_axis] [get_bd_intf_pins cpu_ram/cpu2cmu_axis]
  connect_bd_intf_net -intf_net mdm_0_MBDEBUG_0 [get_bd_intf_pins mdm_0/MBDEBUG_0] [get_bd_intf_pins microblaze_0/DEBUG]
  connect_bd_intf_net -intf_net microblaze_0_DLMB [get_bd_intf_pins mb_lmb/DLMB] [get_bd_intf_pins microblaze_0/DLMB]
  connect_bd_intf_net -intf_net microblaze_0_ILMB [get_bd_intf_pins mb_lmb/ILMB] [get_bd_intf_pins microblaze_0/ILMB]
  connect_bd_intf_net -intf_net microblaze_0_M_AXI_DP [get_bd_intf_pins microblaze_0/M_AXI_DP] [get_bd_intf_pins microblaze_0_axi_periph/S00_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M00_AXI [get_bd_intf_pins M00_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M00_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M01_AXI [get_bd_intf_pins mdm_0/S_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M01_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M02_AXI [get_bd_intf_pins M02_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M02_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M03_AXI [get_bd_intf_pins axi_intc_0/s_axi] [get_bd_intf_pins microblaze_0_axi_periph/M03_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M04_AXI [get_bd_intf_pins axi_timer_0/S_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M04_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M05_AXI [get_bd_intf_pins cpu_ram/cpu_bram_S_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M05_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M06_AXI [get_bd_intf_pins cpu_ram/cpu_ram_S_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M06_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M07_AXI [get_bd_intf_pins axi_quad_spi_0/AXI_LITE] [get_bd_intf_pins microblaze_0_axi_periph/M07_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M08_AXI [get_bd_intf_pins axi_gpio_0/S_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M08_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M09_AXI [get_bd_intf_pins axi_iic_0/S_AXI] [get_bd_intf_pins microblaze_0_axi_periph/M09_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M10_AXI [get_bd_intf_pins M10_AXI_DAQ] [get_bd_intf_pins microblaze_0_axi_periph/M10_AXI]
  connect_bd_intf_net -intf_net udp2cpu_axis_1 [get_bd_intf_pins cmu2cpu_axis] [get_bd_intf_pins cpu_ram/cmu2cpu_axis]

  # Create port connections
  connect_bd_net -net LMB_Rst_1 [get_bd_pins cpu_ram/rst] [get_bd_pins mb_lmb/LMB_Rst] [get_bd_pins rst_clk_wiz_100M/bus_struct_reset]
  connect_bd_net -net Net [get_bd_pins axi_quad_spi_0/sck_i] [get_bd_pins axi_quad_spi_0/sck_o] [get_bd_pins spi_io_0/spi_clk]
  connect_bd_net -net Net1 [get_bd_pins axi_quad_spi_0/io0_i] [get_bd_pins axi_quad_spi_0/io0_o] [get_bd_pins spi_io_0/spi_sdo]
  connect_bd_net -net Net2 [get_bd_pins axi_quad_spi_0/ss_i] [get_bd_pins axi_quad_spi_0/ss_o] [get_bd_pins spi_io_0/spi_csn]
  connect_bd_net -net axi_iic_0_gpo [get_bd_pins gpo_0] [get_bd_pins axi_iic_0/gpo]
  connect_bd_net -net axi_timer_0_interrupt [get_bd_pins axi_timer_0/interrupt] [get_bd_pins xlconcat_0/In0]
  connect_bd_net -net clk_wiz_clk_out1 [get_bd_pins cpu_clk] [get_bd_pins axi_gpio_0/s_axi_aclk] [get_bd_pins axi_iic_0/s_axi_aclk] [get_bd_pins axi_intc_0/s_axi_aclk] [get_bd_pins axi_quad_spi_0/ext_spi_clk] [get_bd_pins axi_quad_spi_0/s_axi_aclk] [get_bd_pins axi_timer_0/s_axi_aclk] [get_bd_pins cpu_ram/cpu_clk] [get_bd_pins mb_lmb/LMB_Clk] [get_bd_pins mdm_0/S_AXI_ACLK] [get_bd_pins microblaze_0/Clk] [get_bd_pins microblaze_0_axi_periph/ACLK] [get_bd_pins microblaze_0_axi_periph/M00_ACLK] [get_bd_pins microblaze_0_axi_periph/M01_ACLK] [get_bd_pins microblaze_0_axi_periph/M02_ACLK] [get_bd_pins microblaze_0_axi_periph/M03_ACLK] [get_bd_pins microblaze_0_axi_periph/M04_ACLK] [get_bd_pins microblaze_0_axi_periph/M05_ACLK] [get_bd_pins microblaze_0_axi_periph/M06_ACLK] [get_bd_pins microblaze_0_axi_periph/M07_ACLK] [get_bd_pins microblaze_0_axi_periph/M08_ACLK] [get_bd_pins microblaze_0_axi_periph/M09_ACLK] [get_bd_pins microblaze_0_axi_periph/M10_ACLK] [get_bd_pins microblaze_0_axi_periph/S00_ACLK] [get_bd_pins rst_clk_wiz_100M/slowest_sync_clk]
  connect_bd_net -net cpu_ram_cpu_ram_intr_o [get_bd_pins cpu_ram/cpu_ram_intr_o] [get_bd_pins xlconcat_0/In2]
  connect_bd_net -net ddr_ctrl_top_0_ui_rst_n [get_bd_pins ext_reset_in] [get_bd_pins rst_clk_wiz_100M/ext_reset_in]
  connect_bd_net -net mdm_0_Debug_SYS_Rst [get_bd_pins mdm_0/Debug_SYS_Rst] [get_bd_pins rst_clk_wiz_100M/mb_debug_sys_rst]
  connect_bd_net -net mdm_0_Interrupt [get_bd_pins mdm_0/Interrupt] [get_bd_pins xlconcat_0/In1]
  connect_bd_net -net rst_clk_wiz_100M_mb_reset [get_bd_pins microblaze_0/Reset] [get_bd_pins rst_clk_wiz_100M/mb_reset]
  connect_bd_net -net rst_clk_wiz_100M_peripheral_aresetn [get_bd_pins cpu_rstn] [get_bd_pins axi_gpio_0/s_axi_aresetn] [get_bd_pins axi_iic_0/s_axi_aresetn] [get_bd_pins axi_intc_0/s_axi_aresetn] [get_bd_pins axi_quad_spi_0/s_axi_aresetn] [get_bd_pins axi_timer_0/s_axi_aresetn] [get_bd_pins cpu_ram/cpu_rstn] [get_bd_pins mdm_0/S_AXI_ARESETN] [get_bd_pins microblaze_0_axi_periph/ARESETN] [get_bd_pins microblaze_0_axi_periph/M00_ARESETN] [get_bd_pins microblaze_0_axi_periph/M01_ARESETN] [get_bd_pins microblaze_0_axi_periph/M02_ARESETN] [get_bd_pins microblaze_0_axi_periph/M03_ARESETN] [get_bd_pins microblaze_0_axi_periph/M04_ARESETN] [get_bd_pins microblaze_0_axi_periph/M05_ARESETN] [get_bd_pins microblaze_0_axi_periph/M06_ARESETN] [get_bd_pins microblaze_0_axi_periph/M07_ARESETN] [get_bd_pins microblaze_0_axi_periph/M08_ARESETN] [get_bd_pins microblaze_0_axi_periph/M09_ARESETN] [get_bd_pins microblaze_0_axi_periph/M10_ARESETN] [get_bd_pins microblaze_0_axi_periph/S00_ARESETN] [get_bd_pins rst_clk_wiz_100M/peripheral_aresetn]
  connect_bd_net -net rst_clk_wiz_100M_peripheral_reset [get_bd_pins peripheral_reset] [get_bd_pins rst_clk_wiz_100M/peripheral_reset]
  connect_bd_net -net spi_io_0_spi_clks [get_bd_pins spi_clks_0] [get_bd_pins spi_io_0/spi_clks]
  connect_bd_net -net spi_io_0_spi_csns [get_bd_pins spi_csns_0] [get_bd_pins spi_io_0/spi_csns]
  connect_bd_net -net spi_io_0_spi_sdi [get_bd_pins axi_quad_spi_0/io1_i] [get_bd_pins spi_io_0/spi_sdi]
  connect_bd_net -net spi_io_0_spi_sdos [get_bd_pins spi_sdos_0] [get_bd_pins spi_io_0/spi_sdos]
  connect_bd_net -net spi_sdis_0_1 [get_bd_pins spi_sdis_0] [get_bd_pins spi_io_0/spi_sdis]
  connect_bd_net -net udp_clk_1 [get_bd_pins cmu_clk] [get_bd_pins cpu_ram/cmu_clk]
  connect_bd_net -net udp_rstn_1 [get_bd_pins cmu_rstn] [get_bd_pins cpu_ram/cmu_rstn]
  connect_bd_net -net xlconcat_0_dout [get_bd_pins axi_intc_0/intr] [get_bd_pins xlconcat_0/dout]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  
# Hierarchical cell: COMM_TOP
proc create_hier_cell_COMM_TOP { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_COMM_TOP() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 cmu2cpu_axis

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 cmu2mem_axis

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 cmu_S_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 cpu2cmu_axis

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:gt_rtl:1.0 gt_sfp_0

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 gt_sfp_refclk_0

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 mem2cmu_axis


  # Create pins
  create_bd_pin -dir I clk_125mhz
  create_bd_pin -dir I -type rst cpu_rstn
  create_bd_pin -dir O -type clk eth_clk
  create_bd_pin -dir O -type rst eth_rstn
  create_bd_pin -dir I -type clk mem_clk
  create_bd_pin -dir I -type rst mem_rstn

  # Create instance: cmu2cpu_fifo, and set properties
  set cmu2cpu_fifo [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 cmu2cpu_fifo ]

  # Create instance: cmu2cpu_width_conv, and set properties
  set cmu2cpu_width_conv [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_dwidth_converter:1.1 cmu2cpu_width_conv ]
  set_property -dict [ list \
   CONFIG.M_TDATA_NUM_BYTES {4} \
   CONFIG.S_TDATA_NUM_BYTES {8} \
 ] $cmu2cpu_width_conv

  # Create instance: cmu2mem_width_conv, and set properties
  set cmu2mem_width_conv [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_dwidth_converter:1.1 cmu2mem_width_conv ]
  set_property -dict [ list \
   CONFIG.HAS_MI_TKEEP {1} \
   CONFIG.M_TDATA_NUM_BYTES {64} \
   CONFIG.S_TDATA_NUM_BYTES {8} \
 ] $cmu2mem_width_conv

  # Create instance: cpu2cmu_fifo, and set properties
  set cpu2cmu_fifo [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 cpu2cmu_fifo ]
  set_property -dict [ list \
   CONFIG.FIFO_MODE {2} \
 ] $cpu2cmu_fifo

  # Create instance: cpu2cmu_width_conv, and set properties
  set cpu2cmu_width_conv [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_dwidth_converter:1.1 cpu2cmu_width_conv ]
  set_property -dict [ list \
   CONFIG.HAS_MI_TKEEP {1} \
   CONFIG.M_TDATA_NUM_BYTES {8} \
   CONFIG.S_TDATA_NUM_BYTES {4} \
 ] $cpu2cmu_width_conv

  # Create instance: ila_0, and set properties
  set ila_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:ila:6.2 ila_0 ]
  set_property -dict [ list \
   CONFIG.C_NUM_OF_PROBES {9} \
   CONFIG.C_SLOT_0_AXI_PROTOCOL {AXI4S} \
 ] $ila_0

  # Create instance: ila_1, and set properties
  set ila_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:ila:6.2 ila_1 ]
  set_property -dict [ list \
   CONFIG.C_NUM_OF_PROBES {9} \
   CONFIG.C_SLOT_0_AXI_PROTOCOL {AXI4S} \
 ] $ila_1

  # Create instance: ila_2, and set properties
  set ila_2 [ create_bd_cell -type ip -vlnv xilinx.com:ip:ila:6.2 ila_2 ]
  set_property -dict [ list \
   CONFIG.C_NUM_OF_PROBES {9} \
   CONFIG.C_SLOT_0_AXI_PROTOCOL {AXI4S} \
 ] $ila_2

  # Create instance: mem2cmu_clock_conv, and set properties
  set mem2cmu_clock_conv [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_clock_converter:1.1 mem2cmu_clock_conv ]

  # Create instance: mem2cmu_width_conv, and set properties
  set mem2cmu_width_conv [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_dwidth_converter:1.1 mem2cmu_width_conv ]
  set_property -dict [ list \
   CONFIG.HAS_MI_TKEEP {0} \
   CONFIG.M_TDATA_NUM_BYTES {8} \
   CONFIG.S_TDATA_NUM_BYTES {64} \
 ] $mem2cmu_width_conv

  # Create instance: tcpip_core_0, and set properties
  set tcpip_core_0 [ create_bd_cell -type ip -vlnv xilinx.com:user:tcpip_core:1.0 tcpip_core_0 ]

  # Create interface connections
  connect_bd_intf_net -intf_net axis_clock_converter_0_M_AXIS [get_bd_intf_pins mem2cmu_clock_conv/M_AXIS] [get_bd_intf_pins mem2cmu_width_conv/S_AXIS]
  connect_bd_intf_net -intf_net axis_dwidth_converter_0_M_AXIS [get_bd_intf_pins cpu2cmu_fifo/M_AXIS] [get_bd_intf_pins tcpip_core_0/tcp0_s_axis]
  connect_bd_intf_net -intf_net [get_bd_intf_nets axis_dwidth_converter_0_M_AXIS] [get_bd_intf_pins cpu2cmu_fifo/M_AXIS] [get_bd_intf_pins ila_2/SLOT_0_AXIS]
  connect_bd_intf_net -intf_net axis_interconnect_1_M00_AXIS [get_bd_intf_pins cmu2mem_axis] [get_bd_intf_pins cmu2mem_width_conv/M_AXIS]
  connect_bd_intf_net -intf_net [get_bd_intf_nets axis_interconnect_1_M00_AXIS] [get_bd_intf_pins cmu2mem_axis] [get_bd_intf_pins ila_0/SLOT_0_AXIS]
  connect_bd_intf_net -intf_net cmu2cpu_dido_M_AXIS [get_bd_intf_pins cmu2cpu_fifo/M_AXIS] [get_bd_intf_pins cmu2cpu_width_conv/S_AXIS]
  connect_bd_intf_net -intf_net cmu2cpu_width_conv_M_AXIS [get_bd_intf_pins cmu2cpu_axis] [get_bd_intf_pins cmu2cpu_width_conv/M_AXIS]
  connect_bd_intf_net -intf_net [get_bd_intf_nets cmu2cpu_width_conv_M_AXIS] [get_bd_intf_pins cmu2cpu_axis] [get_bd_intf_pins ila_1/SLOT_0_AXIS]
  connect_bd_intf_net -intf_net cmu_S_AXI_1 [get_bd_intf_pins cmu_S_AXI] [get_bd_intf_pins tcpip_core_0/S_AXI]
  connect_bd_intf_net -intf_net cpu2cmu_axis_1 [get_bd_intf_pins cpu2cmu_axis] [get_bd_intf_pins cpu2cmu_width_conv/S_AXIS]
  connect_bd_intf_net -intf_net cpu2cmu_width_conv_M_AXIS [get_bd_intf_pins cpu2cmu_fifo/S_AXIS] [get_bd_intf_pins cpu2cmu_width_conv/M_AXIS]
  connect_bd_intf_net -intf_net ddr_ctrl_top_0_M_AXIS [get_bd_intf_pins mem2cmu_axis] [get_bd_intf_pins mem2cmu_clock_conv/S_AXIS]
  connect_bd_intf_net -intf_net gt_sfp_refclk_0_1 [get_bd_intf_pins gt_sfp_refclk_0] [get_bd_intf_pins tcpip_core_0/gt_sfp_refclk]
  connect_bd_intf_net -intf_net mem2cmu_width_conv_M_AXIS [get_bd_intf_pins mem2cmu_width_conv/M_AXIS] [get_bd_intf_pins tcpip_core_0/tcp1_s_axis]
  connect_bd_intf_net -intf_net tcpip_core_0_gt_sfp [get_bd_intf_pins gt_sfp_0] [get_bd_intf_pins tcpip_core_0/gt_sfp]
  connect_bd_intf_net -intf_net tcpip_core_0_tcp0_m_axis [get_bd_intf_pins cmu2cpu_fifo/S_AXIS] [get_bd_intf_pins tcpip_core_0/tcp0_m_axis]
  connect_bd_intf_net -intf_net tcpip_core_0_tcp1_m_axis [get_bd_intf_pins cmu2mem_width_conv/S_AXIS] [get_bd_intf_pins tcpip_core_0/tcp1_m_axis]

  # Create port connections
  connect_bd_net -net ACLK_1 [get_bd_pins mem_clk] [get_bd_pins mem2cmu_clock_conv/s_axis_aclk]
  connect_bd_net -net Net [get_bd_pins eth_clk] [get_bd_pins cmu2cpu_fifo/s_axis_aclk] [get_bd_pins cmu2cpu_width_conv/aclk] [get_bd_pins cmu2mem_width_conv/aclk] [get_bd_pins cpu2cmu_fifo/s_axis_aclk] [get_bd_pins cpu2cmu_width_conv/aclk] [get_bd_pins ila_0/clk] [get_bd_pins ila_1/clk] [get_bd_pins ila_2/clk] [get_bd_pins mem2cmu_clock_conv/m_axis_aclk] [get_bd_pins mem2cmu_width_conv/aclk] [get_bd_pins tcpip_core_0/axis_aclk]
  connect_bd_net -net Net1 [get_bd_pins eth_rstn] [get_bd_pins cmu2cpu_fifo/s_axis_aresetn] [get_bd_pins cmu2cpu_width_conv/aresetn] [get_bd_pins cmu2mem_width_conv/aresetn] [get_bd_pins cpu2cmu_fifo/s_axis_aresetn] [get_bd_pins cpu2cmu_width_conv/aresetn] [get_bd_pins mem2cmu_clock_conv/m_axis_aresetn] [get_bd_pins mem2cmu_width_conv/aresetn] [get_bd_pins tcpip_core_0/axis_aresetn]
  connect_bd_net -net clk_wiz_clk_out1 [get_bd_pins clk_125mhz] [get_bd_pins tcpip_core_0/S_AXI_aclk] [get_bd_pins tcpip_core_0/clk_125mhz]
  connect_bd_net -net ddr_ctrl_top_0_ui_rst_n [get_bd_pins mem_rstn] [get_bd_pins mem2cmu_clock_conv/s_axis_aresetn]
  connect_bd_net -net rst_clk_wiz_100M_peripheral_aresetn [get_bd_pins cpu_rstn] [get_bd_pins tcpip_core_0/S_AXI_aresetn]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set GPIO2_0 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 GPIO2_0 ]

  set GPIO_0 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 GPIO_0 ]

  set IIC [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:iic_rtl:1.0 IIC ]

  set c0_ddr4_0 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 c0_ddr4_0 ]

  set gt_sfp_0 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gt_rtl:1.0 gt_sfp_0 ]

  set gt_sfp_refclk_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 gt_sfp_refclk_0 ]


  # Create ports
  set AD1_CSB [ create_bd_port -dir O -from 0 -to 0 AD1_CSB ]
  set ADC_SCLK [ create_bd_port -dir O -from 0 -to 0 ADC_SCLK ]
  set ADC_SDIO [ create_bd_port -dir O -from 0 -to 0 ADC_SDIO ]
  set CLK_200MM_N [ create_bd_port -dir I CLK_200MM_N ]
  set CLK_200MM_P [ create_bd_port -dir I CLK_200MM_P ]
  set EXT_PLL_LOCK [ create_bd_port -dir I -from 0 -to 0 EXT_PLL_LOCK ]
  set F_CLK_SEL [ create_bd_port -dir O -from 0 -to 0 F_CLK_SEL ]
  set LED [ create_bd_port -dir O -from 3 -to 0 LED ]
  set PLL_CLK_N [ create_bd_port -dir I -from 0 -to 0 PLL_CLK_N ]
  set PLL_CLK_P [ create_bd_port -dir I -from 0 -to 0 PLL_CLK_P ]
  set PLL_CS [ create_bd_port -dir O -from 0 -to 0 PLL_CS ]
  set PLL_RESETN [ create_bd_port -dir O -from 0 -to 0 PLL_RESETN ]
  set PLL_SCLK [ create_bd_port -dir O -from 0 -to 0 PLL_SCLK ]
  set PLL_SDIO [ create_bd_port -dir O -from 0 -to 0 PLL_SDIO ]
  set PLL_SDO [ create_bd_port -dir I -from 0 -to 0 PLL_SDO ]
  set ad9653_ifc_n_0 [ create_bd_port -dir I -from 9 -to 0 ad9653_ifc_n_0 ]
  set ad9653_ifc_p_0 [ create_bd_port -dir I -from 9 -to 0 ad9653_ifc_p_0 ]
  set adc_sync_0 [ create_bd_port -dir O -from 0 -to 0 adc_sync_0 ]
  set c0_sys_clk_n [ create_bd_port -dir I c0_sys_clk_n ]
  set c0_sys_clk_p [ create_bd_port -dir I c0_sys_clk_p ]
  set reset [ create_bd_port -dir I -type rst reset ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_HIGH} \
 ] $reset
  set spi_clks_0 [ create_bd_port -dir O -from 2 -to 0 spi_clks_0 ]
  set spi_csns_0 [ create_bd_port -dir O -from 2 -to 0 spi_csns_0 ]
  set spi_sdis_0 [ create_bd_port -dir I -from 2 -to 0 spi_sdis_0 ]
  set spi_sdos_0 [ create_bd_port -dir O -from 2 -to 0 spi_sdos_0 ]
  set trig_input [ create_bd_port -dir I trig_input ]

  # Create instance: COMM_TOP
  create_hier_cell_COMM_TOP [current_bd_instance .] COMM_TOP

  # Create instance: CPU_TOP
  create_hier_cell_CPU_TOP [current_bd_instance .] CPU_TOP

  # Create instance: DAQ_TOP
  create_hier_cell_DAQ_TOP [current_bd_instance .] DAQ_TOP

  # Create instance: MEM_TOP
  create_hier_cell_MEM_TOP [current_bd_instance .] MEM_TOP

  # Create instance: rst_inv, and set properties
  set rst_inv [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic:2.0 rst_inv ]
  set_property -dict [ list \
   CONFIG.C_OPERATION {not} \
   CONFIG.C_SIZE {1} \
   CONFIG.LOGO_FILE {data/sym_notgate.png} \
 ] $rst_inv

  # Create interface connections
  connect_bd_intf_net -intf_net COMM_TOP_cmu2cpu_axis [get_bd_intf_pins COMM_TOP/cmu2cpu_axis] [get_bd_intf_pins CPU_TOP/cmu2cpu_axis]
  connect_bd_intf_net -intf_net CPU_TOP_GPIO2_0 [get_bd_intf_ports GPIO2_0] [get_bd_intf_pins CPU_TOP/GPIO2_0]
  connect_bd_intf_net -intf_net CPU_TOP_GPIO_0 [get_bd_intf_ports GPIO_0] [get_bd_intf_pins CPU_TOP/GPIO_0]
  connect_bd_intf_net -intf_net CPU_TOP_IIC_0 [get_bd_intf_ports IIC] [get_bd_intf_pins CPU_TOP/IIC_0]
  connect_bd_intf_net -intf_net CPU_TOP_M10_AXI_DAQ [get_bd_intf_pins CPU_TOP/M10_AXI_DAQ] [get_bd_intf_pins DAQ_TOP/S_AXI_DAQ]
  connect_bd_intf_net -intf_net CPU_TOP_cpu2udp_axis [get_bd_intf_pins COMM_TOP/cpu2cmu_axis] [get_bd_intf_pins CPU_TOP/cpu2cmu_axis]
  connect_bd_intf_net -intf_net MEM_TOP_c0_ddr4_0 [get_bd_intf_ports c0_ddr4_0] [get_bd_intf_pins MEM_TOP/c0_ddr4_0]
  connect_bd_intf_net -intf_net S_daq2mem_axis_1 [get_bd_intf_pins DAQ_TOP/m_rd_axis] [get_bd_intf_pins MEM_TOP/S_daq2mem_axis]
  connect_bd_intf_net -intf_net ddr_ctrl_top_0_M_AXIS [get_bd_intf_pins COMM_TOP/mem2cmu_axis] [get_bd_intf_pins MEM_TOP/M_AXIS]
  connect_bd_intf_net -intf_net gt_sfp_refclk_0_1 [get_bd_intf_ports gt_sfp_refclk_0] [get_bd_intf_pins COMM_TOP/gt_sfp_refclk_0]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M00_AXI [get_bd_intf_pins CPU_TOP/M00_AXI] [get_bd_intf_pins MEM_TOP/S_AXI]
  connect_bd_intf_net -intf_net microblaze_0_axi_periph_M02_AXI [get_bd_intf_pins COMM_TOP/cmu_S_AXI] [get_bd_intf_pins CPU_TOP/M02_AXI]
  connect_bd_intf_net -intf_net udp_2_mem_process_0_m_axis [get_bd_intf_pins COMM_TOP/cmu2mem_axis] [get_bd_intf_pins MEM_TOP/S_AXIS]
  connect_bd_intf_net -intf_net udp_eth_0_gt_sfp [get_bd_intf_ports gt_sfp_0] [get_bd_intf_pins COMM_TOP/gt_sfp_0]

  # Create port connections
  connect_bd_net -net ACLK_1 [get_bd_pins COMM_TOP/mem_clk] [get_bd_pins MEM_TOP/mem_clk]
  connect_bd_net -net CLK_200MM_N_1 [get_bd_ports CLK_200MM_N] [get_bd_pins DAQ_TOP/CLK_200M_N]
  connect_bd_net -net CLK_200MM_P_1 [get_bd_ports CLK_200MM_P] [get_bd_pins DAQ_TOP/CLK_200M_P]
  connect_bd_net -net CPU_TOP_spi_clks_0 [get_bd_ports spi_clks_0] [get_bd_pins CPU_TOP/spi_clks_0]
  connect_bd_net -net CPU_TOP_spi_csns_0 [get_bd_ports spi_csns_0] [get_bd_pins CPU_TOP/spi_csns_0]
  connect_bd_net -net CPU_TOP_spi_sdos_0 [get_bd_ports spi_sdos_0] [get_bd_pins CPU_TOP/spi_sdos_0]
  connect_bd_net -net DAQ_TOP_AD1_CSB [get_bd_ports AD1_CSB] [get_bd_pins DAQ_TOP/AD1_CSB]
  connect_bd_net -net DAQ_TOP_ADC_SCLK [get_bd_ports ADC_SCLK] [get_bd_pins DAQ_TOP/ADC_SCLK]
  connect_bd_net -net DAQ_TOP_ADC_SDIO [get_bd_ports ADC_SDIO] [get_bd_pins DAQ_TOP/ADC_SDIO]
  connect_bd_net -net DAQ_TOP_F_CLK_SEL [get_bd_ports F_CLK_SEL] [get_bd_pins DAQ_TOP/F_CLK_SEL]
  connect_bd_net -net DAQ_TOP_LED [get_bd_ports LED] [get_bd_pins DAQ_TOP/LED]
  connect_bd_net -net DAQ_TOP_PLL_CS [get_bd_ports PLL_CS] [get_bd_pins DAQ_TOP/PLL_CS]
  connect_bd_net -net DAQ_TOP_PLL_RESETN [get_bd_ports PLL_RESETN] [get_bd_pins DAQ_TOP/PLL_RESETN]
  connect_bd_net -net DAQ_TOP_PLL_SCLK [get_bd_ports PLL_SCLK] [get_bd_pins DAQ_TOP/PLL_SCLK]
  connect_bd_net -net DAQ_TOP_PLL_SDIO [get_bd_ports PLL_SDIO] [get_bd_pins DAQ_TOP/PLL_SDIO]
  connect_bd_net -net DAQ_TOP_adc_sync_0 [get_bd_ports adc_sync_0] [get_bd_pins DAQ_TOP/adc_sync_0]
  connect_bd_net -net DAQ_TOP_daq_rstn [get_bd_pins DAQ_TOP/daq_rstn] [get_bd_pins MEM_TOP/daq_rstn]
  connect_bd_net -net EXT_PLL_LOCK_0_1 [get_bd_ports EXT_PLL_LOCK] [get_bd_pins DAQ_TOP/EXT_PLL_LOCK]
  connect_bd_net -net Net [get_bd_pins COMM_TOP/eth_clk] [get_bd_pins CPU_TOP/cmu_clk] [get_bd_pins MEM_TOP/eth_clk]
  connect_bd_net -net Net1 [get_bd_pins COMM_TOP/eth_rstn] [get_bd_pins CPU_TOP/cmu_rstn] [get_bd_pins MEM_TOP/eth_rstn]
  connect_bd_net -net PLL_CLK_N_0_1 [get_bd_ports PLL_CLK_N] [get_bd_pins DAQ_TOP/PLL_CLK_N]
  connect_bd_net -net PLL_CLK_P_0_1 [get_bd_ports PLL_CLK_P] [get_bd_pins DAQ_TOP/PLL_CLK_P]
  connect_bd_net -net PLL_SDO_0_1 [get_bd_ports PLL_SDO] [get_bd_pins DAQ_TOP/PLL_SDO]
  connect_bd_net -net ad9653_ifc_n_0_1 [get_bd_ports ad9653_ifc_n_0] [get_bd_pins DAQ_TOP/ad9653_ifc_n_0]
  connect_bd_net -net ad9653_ifc_p_0_1 [get_bd_ports ad9653_ifc_p_0] [get_bd_pins DAQ_TOP/ad9653_ifc_p_0]
  connect_bd_net -net c0_sys_clk_n_1 [get_bd_ports c0_sys_clk_n] [get_bd_pins MEM_TOP/c0_sys_clk_n]
  connect_bd_net -net c0_sys_clk_p_1 [get_bd_ports c0_sys_clk_p] [get_bd_pins MEM_TOP/c0_sys_clk_p]
  connect_bd_net -net clk_wiz_clk_out1 [get_bd_pins COMM_TOP/clk_125mhz] [get_bd_pins CPU_TOP/cpu_clk] [get_bd_pins DAQ_TOP/cpu_clk] [get_bd_pins MEM_TOP/cpu_clk]
  connect_bd_net -net daq_clk_1 [get_bd_pins DAQ_TOP/daq_clk] [get_bd_pins MEM_TOP/daq_clk]
  connect_bd_net -net ddr_ctrl_top_0_ui_rst_n [get_bd_pins COMM_TOP/mem_rstn] [get_bd_pins MEM_TOP/mem_rstn]
  connect_bd_net -net ext_reset_in_1 [get_bd_pins CPU_TOP/ext_reset_in] [get_bd_pins DAQ_TOP/reset] [get_bd_pins rst_inv/Res]
  connect_bd_net -net external_trig_0_1 [get_bd_ports trig_input] [get_bd_pins DAQ_TOP/external_trig_0]
  connect_bd_net -net reset_1 [get_bd_ports reset] [get_bd_pins rst_inv/Op1]
  connect_bd_net -net rst_clk_wiz_100M_peripheral_aresetn [get_bd_pins COMM_TOP/cpu_rstn] [get_bd_pins CPU_TOP/cpu_rstn] [get_bd_pins DAQ_TOP/cpu_rstn] [get_bd_pins MEM_TOP/cpu_rstn]
  connect_bd_net -net rst_clk_wiz_100M_peripheral_reset [get_bd_pins CPU_TOP/peripheral_reset] [get_bd_pins MEM_TOP/sys_rst]
  connect_bd_net -net spi_sdis_0_1 [get_bd_ports spi_sdis_0] [get_bd_pins CPU_TOP/spi_sdis_0]

  # Create address segments
  assign_bd_address -offset 0x00170000 -range 0x00002000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs CPU_TOP/cpu_ram/axi_bram_ctrl_0/S_AXI/Mem0] -force
  assign_bd_address -offset 0x00110000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs CPU_TOP/axi_gpio_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x00120000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs CPU_TOP/axi_iic_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x00130000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs CPU_TOP/axi_intc_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x00150000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs CPU_TOP/axi_quad_spi_0/AXI_LITE/Reg] -force
  assign_bd_address -offset 0x00160000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs CPU_TOP/axi_timer_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x00180000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs CPU_TOP/cpu_ram/cpu_ram_0/S_AXI/reg0] -force
  assign_bd_address -offset 0x00140000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs MEM_TOP/ddr_ctrl_top_1/S_AXI/reg0] -force
  assign_bd_address -offset 0x00000000 -range 0x00020000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs CPU_TOP/mb_lmb/dlmb_bram_if_cntlr/SLMB/Mem] -force
  assign_bd_address -offset 0x001B0000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs DAQ_TOP/fifo_top_0/S_AXI/reg0] -force
  assign_bd_address -offset 0x00000000 -range 0x00020000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Instruction] [get_bd_addr_segs CPU_TOP/mb_lmb/ilmb_bram_if_cntlr/SLMB/Mem] -force
  assign_bd_address -offset 0x00190000 -range 0x00001000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs CPU_TOP/mdm_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x00100000 -range 0x00010000 -target_address_space [get_bd_addr_spaces CPU_TOP/microblaze_0/Data] [get_bd_addr_segs COMM_TOP/tcpip_core_0/S_AXI/reg0] -force

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"0.778723",
   "Default View_TopLeft":"-369,0",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.0r6  2020-01-29 bk=1.5227 VDI=41 GEI=36 GUI=JA:10.0 non-TLS
#  -string -flagsOSRD
preplace port GPIO2_0 -pg 1 -lvl 4 -x 1250 -y 70 -defaultsOSRD
preplace port GPIO_0 -pg 1 -lvl 4 -x 1250 -y 90 -defaultsOSRD
preplace port IIC -pg 1 -lvl 4 -x 1250 -y 110 -defaultsOSRD
preplace port c0_ddr4_0 -pg 1 -lvl 4 -x 1250 -y 410 -defaultsOSRD
preplace port gt_sfp_0 -pg 1 -lvl 4 -x 1250 -y 360 -defaultsOSRD
preplace port gt_sfp_refclk_0 -pg 1 -lvl 0 -x 0 -y 30 -defaultsOSRD
preplace port CLK_200MM_N -pg 1 -lvl 0 -x 0 -y 670 -defaultsOSRD
preplace port CLK_200MM_P -pg 1 -lvl 0 -x 0 -y 690 -defaultsOSRD
preplace port reset -pg 1 -lvl 0 -x 0 -y 480 -defaultsOSRD
preplace port trig_input -pg 1 -lvl 0 -x 0 -y 870 -defaultsOSRD
preplace port c0_sys_clk_p -pg 1 -lvl 0 -x 0 -y 190 -defaultsOSRD
preplace port c0_sys_clk_n -pg 1 -lvl 0 -x 0 -y 170 -defaultsOSRD
preplace portBus AD1_CSB -pg 1 -lvl 4 -x 1250 -y 670 -defaultsOSRD
preplace portBus ADC_SCLK -pg 1 -lvl 4 -x 1250 -y 690 -defaultsOSRD
preplace portBus ADC_SDIO -pg 1 -lvl 4 -x 1250 -y 710 -defaultsOSRD
preplace portBus EXT_PLL_LOCK -pg 1 -lvl 0 -x 0 -y 710 -defaultsOSRD
preplace portBus F_CLK_SEL -pg 1 -lvl 4 -x 1250 -y 730 -defaultsOSRD
preplace portBus LED -pg 1 -lvl 4 -x 1250 -y 750 -defaultsOSRD
preplace portBus PLL_CLK_N -pg 1 -lvl 0 -x 0 -y 730 -defaultsOSRD
preplace portBus PLL_CLK_P -pg 1 -lvl 0 -x 0 -y 750 -defaultsOSRD
preplace portBus PLL_CS -pg 1 -lvl 4 -x 1250 -y 770 -defaultsOSRD
preplace portBus PLL_RESETN -pg 1 -lvl 4 -x 1250 -y 790 -defaultsOSRD
preplace portBus PLL_SCLK -pg 1 -lvl 4 -x 1250 -y 810 -defaultsOSRD
preplace portBus PLL_SDIO -pg 1 -lvl 4 -x 1250 -y 830 -defaultsOSRD
preplace portBus PLL_SDO -pg 1 -lvl 0 -x 0 -y 770 -defaultsOSRD
preplace portBus ad9653_ifc_n_0 -pg 1 -lvl 0 -x 0 -y 790 -defaultsOSRD
preplace portBus ad9653_ifc_p_0 -pg 1 -lvl 0 -x 0 -y 810 -defaultsOSRD
preplace portBus adc_sync_0 -pg 1 -lvl 4 -x 1250 -y 850 -defaultsOSRD
preplace portBus spi_clks_0 -pg 1 -lvl 4 -x 1250 -y 270 -defaultsOSRD
preplace portBus spi_csns_0 -pg 1 -lvl 4 -x 1250 -y 290 -defaultsOSRD
preplace portBus spi_sdis_0 -pg 1 -lvl 0 -x 0 -y 420 -defaultsOSRD
preplace portBus spi_sdos_0 -pg 1 -lvl 4 -x 1250 -y 310 -defaultsOSRD
preplace inst COMM_TOP -pg 1 -lvl 2 -x 600 -y 240 -defaultsOSRD
preplace inst CPU_TOP -pg 1 -lvl 3 -x 1010 -y 190 -defaultsOSRD
preplace inst DAQ_TOP -pg 1 -lvl 3 -x 1010 -y 770 -defaultsOSRD
preplace inst MEM_TOP -pg 1 -lvl 1 -x 240 -y 210 -defaultsOSRD
preplace inst rst_inv -pg 1 -lvl 2 -x 600 -y 480 -defaultsOSRD
preplace netloc ACLK_1 1 1 1 410 230n
preplace netloc CLK_200MM_N_1 1 0 3 NJ 670 NJ 670 NJ
preplace netloc CLK_200MM_P_1 1 0 3 NJ 690 NJ 690 NJ
preplace netloc CPU_TOP_spi_clks_0 1 3 1 NJ 270
preplace netloc CPU_TOP_spi_csns_0 1 3 1 NJ 290
preplace netloc CPU_TOP_spi_sdos_0 1 3 1 NJ 310
preplace netloc DAQ_TOP_AD1_CSB 1 3 1 NJ 670
preplace netloc DAQ_TOP_ADC_SCLK 1 3 1 NJ 690
preplace netloc DAQ_TOP_ADC_SDIO 1 3 1 NJ 710
preplace netloc DAQ_TOP_F_CLK_SEL 1 3 1 NJ 730
preplace netloc DAQ_TOP_LED 1 3 1 NJ 750
preplace netloc DAQ_TOP_PLL_CS 1 3 1 NJ 770
preplace netloc DAQ_TOP_PLL_RESETN 1 3 1 NJ 790
preplace netloc DAQ_TOP_PLL_SCLK 1 3 1 NJ 810
preplace netloc DAQ_TOP_PLL_SDIO 1 3 1 NJ 830
preplace netloc DAQ_TOP_adc_sync_0 1 3 1 NJ 850
preplace netloc DAQ_TOP_daq_rstn 1 0 4 60 550 NJ 550 NJ 550 1170
preplace netloc EXT_PLL_LOCK_0_1 1 0 3 NJ 710 NJ 710 NJ
preplace netloc Net 1 0 3 30 20 NJ 20 770
preplace netloc Net1 1 0 3 40 40 NJ 40 760
preplace netloc PLL_CLK_N_0_1 1 0 3 NJ 730 NJ 730 NJ
preplace netloc PLL_CLK_P_0_1 1 0 3 NJ 750 NJ 750 NJ
preplace netloc PLL_SDO_0_1 1 0 3 NJ 770 NJ 770 NJ
preplace netloc ad9653_ifc_n_0_1 1 0 3 NJ 790 NJ 790 NJ
preplace netloc ad9653_ifc_p_0_1 1 0 3 NJ 810 NJ 810 NJ
preplace netloc clk_wiz_clk_out1 1 1 2 400 360 790
preplace netloc daq_clk_1 1 0 4 50 540 NJ 540 NJ 540 1180
preplace netloc ddr_ctrl_top_0_ui_rst_n 1 1 1 380 250n
preplace netloc ext_reset_in_1 1 2 1 840 220n
preplace netloc external_trig_0_1 1 0 3 NJ 870 NJ 870 NJ
preplace netloc reset_1 1 0 2 NJ 480 NJ
preplace netloc rst_clk_wiz_100M_peripheral_aresetn 1 0 4 80 360 390 400 830 400 1180
preplace netloc rst_clk_wiz_100M_peripheral_reset 1 0 4 90 410 410J 420 NJ 420 1170
preplace netloc spi_sdis_0_1 1 0 3 NJ 420 440J 410 810J
preplace netloc c0_sys_clk_p_1 1 0 1 N 190
preplace netloc c0_sys_clk_n_1 1 0 1 N 170
preplace netloc MEM_TOP_c0_ddr4_0 1 1 3 400J 110 820J 410 NJ
preplace netloc microblaze_0_axi_periph_M00_AXI 1 0 4 20 380 NJ 380 NJ 380 1210
preplace netloc CPU_TOP_M10_AXI_DAQ 1 2 2 850 430 1230
preplace netloc microblaze_0_axi_periph_M02_AXI 1 1 3 450 390 NJ 390 1200
preplace netloc CPU_TOP_GPIO_0 1 3 1 NJ 90
preplace netloc ddr_ctrl_top_0_M_AXIS 1 1 1 420 170n
preplace netloc gt_sfp_refclk_0_1 1 0 2 NJ 30 430J
preplace netloc udp_eth_0_gt_sfp 1 2 2 800J 360 NJ
preplace netloc udp_2_mem_process_0_m_axis 1 0 3 80 50 NJ 50 750
preplace netloc COMM_TOP_cmu2cpu_axis 1 2 1 780 140n
preplace netloc CPU_TOP_IIC_0 1 3 1 NJ 110
preplace netloc CPU_TOP_cpu2udp_axis 1 1 3 440 10 NJ 10 1220
preplace netloc S_daq2mem_axis_1 1 0 4 70 370 NJ 370 NJ 370 1190
preplace netloc CPU_TOP_GPIO2_0 1 3 1 NJ 70
levelinfo -pg 1 0 240 600 1010 1250
pagesize -pg 1 -db -bbox -sgen -190 0 1420 940
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_system()
cr_bd_system ""
set_property REGISTERED_WITH_MANAGER "1" [get_files system.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files system.bd ] 

#call make_wrapper to create wrapper files
if { [get_property IS_LOCKED [ get_files -norecurse system.bd] ] == 1  } {
  import_files -fileset sources_1 [file normalize "${origin_dir}/../prj_zyf/_xil_proj_name_.gen/sources_1/bd/system/hdl/system_wrapper.v" ]
} else {
  set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse system.bd] -top]
  add_files -norecurse -fileset sources_1 $wrapper_path
}


# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcku040-ffva1156-2-i -flow {Vivado Synthesis 2020} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2020" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xcku040-ffva1156-2-i" -objects $obj
set_property -name "auto_incremental_checkpoint.directory" -value "E:/git_vivado/git_vivado/_xil_proj_name_/_xil_proj_name_.srcs/utils_1/imports/synth_1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcku040-ffva1156-2-i -flow {Vivado Implementation 2020} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2020" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xcku040-ffva1156-2-i" -objects $obj
set_property -name "auto_incremental_checkpoint.directory" -value "E:/git_vivado/git_vivado/_xil_proj_name_/_xil_proj_name_.srcs/utils_1/imports/impl_1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
